### ISSUE TITLE
Question about vertical insets

### ISSUE THREAD

**Issue by FWDekker** [JetBrains/ui#15]
Not sure where to ask for clarifications on the guidelines so I'll just do it here.

The [Layout page](https://jetbrains.github.io/ui/principles/layout/) has a section about groups of controls. It is mentioned that small groups can be separated by vertical insets. However, it is not clear to me
1. what the canonical way of creating such an inset is (should I use a `VSpacer` or is there a special component for this?)
2. what the desired height for the spacing is (10 pixels, 50 pixels, and what if the user scales the UI?).

I think the guidelines would benefit from clarifying these details.

**Comment by OlyaB** [comment]
Thank you for the questions. We are planning to add code snippets to this article, they would cover this information. I will write here once we have snippets.

**Comment by karollewandowski** [comment]
Hi, the issue has been transferred to YouTrack: https://youtrack.jetbrains.com/issue/IJSDK-2066/UI-Guidelines-Question-about-vertical-insets
