### ISSUE TITLE
Poor Icons search performance on https://jetbrains.design/

### ISSUE THREAD

**Issue by smokeelow** [JetBrains/ui#17]
Could you please improve icons page performance https://jetbrains.design/intellij/resources/icons_list/

I have pretty powerful mac but when i'm starting to search icons UI hangs for couple seconds (2-5 sec)

![image](https://user-images.githubusercontent.com/1822237/77480861-2add0b80-6e2b-11ea-9ac5-262e4bf0148c.png)

**Comment by c5inco** [comment]
Thanks for the feedback! Yes, we've seen the performance of the page get quite slow, especially as we've added more and more icons, so we'll be actively looking at a solution soon.

And it's not your Mac - it's our code that is not written efficiently.

**Comment by smokeelow** [comment]
@c5inco thanks!

**Comment by c5inco** [comment]
Hello - we finally got the fix done! The site performance should be much, much better now. @smokeelow please try it out and let us know!

**Comment by smokeelow** [comment]
Hello @c5inco. 
Awesome, now it works perfect. Thanks!
