### ISSUE TITLE
Search field class never mentioned

### ISSUE THREAD

**Issue by RRMoelker** [JetBrains/ui#19]
The Search field control class is not mentioned eventhough the rest of the document seems to be finished.

This page: https://jetbrains.github.io/ui/controls/search_field/ does not state the class instead shows "To be implemented". Please mention which class to use.

_On a side note, the whole plugin development documentation is very spartan. I'm actually quite surprised there are so many good plugins out there given how hard it is to develop one._

**Comment by YannCebron** [comment]
Thanks for spotting! 
Speed Search (popup search over tree/list/table): https://www.jetbrains.org/intellij/sdk/docs/user_interface_components/lists_and_trees.html#listspeedsearch-and-treespeedsearch

Generic text field with search icon/history: `com.intellij.ui.SearchTextField`

You can also use "UI Inspector" tool to locate underlying Swing components (or debug them) at runtime, see https://www.jetbrains.org/intellij/sdk/docs/reference_guide/internal_actions/internal_uii.html

**Comment by RRMoelker** [comment]
com.intellij.ui.SearchTextField works brilliantly. Thank you.

And the UI Inspector is a great tool. I'm surely going to be using that a lot from here on.

The mention of the UI Inspector is a bit in the background now in the documentation. I suggest it is also mentioned in the "[User Interface Components](https://www.jetbrains.org/intellij/sdk/docs/user_interface_components/user_interface_components.html)" section. Because there seem to be a lot more components available than the ones discussed.

Right now, there is no clear way on how to know which UI components are available. I was simply trying all J or JB classes, e.g. JBTextField. Having this UI inspector is going to be handy for many others as well.

**Comment by YannCebron** [comment]
In fact I've been adding the reference to UI Inspector as you suggested just before replying here :)

**Comment by yzozulya** [comment]
Updated the docs with the above-mentioned class.
