### ISSUE TITLE
There is no style for a Filled, Split Button

### ISSUE THREAD

**Issue by ciscorucinski** [JetBrains/ui#20]
For the button style, there are 2 types:
 - Filled button
 - outline button

However, for the split button, there is only the outline button.

I was looking at [JetBrains' YouTrack website](https://youtrack.jetbrains.com/) and noticed the `New Issue` button would highly benefit from a filled button style rather than an outline style.

YouTrack Reported Issue: https://youtrack.jetbrains.com/issue/JT-58264

**Comment by mishinalina** [comment]
Thank you for the report. These guidelines are for JetBrains IDEs, which are desktop products. The web products such as YouTrack have their own guidelines. Please use YouTrack to report issues about YouTrack product :)
