### ISSUE TITLE
Missing render-1_dark.svg  icon

### ISSUE THREAD

**Issue by hsz** [JetBrains/ui#22]
There is a 404 for `render-1_dark.svg` icon: 
![image](https://user-images.githubusercontent.com/108333/86796349-c870e980-c06e-11ea-9c9c-f4a1e7899eb7.png)

Failing URL: https://intellij-icons.jetbrains.design/icons/RIcons/icons/render-1_dark.svg

**Comment by c5inco** [comment]
Thanks for finding that! Seems like that is a duplicate icon that is not needed. @mishinalina please confirm.

**Comment by mishinalina** [comment]
Thank you for the report! We fixed the problem.
