### ISSUE TITLE
SVG Icon licensing

### ISSUE THREAD

**Issue by dstovall** [JetBrains/ui#27]
Are the [SVG Icons](https://jetbrains.design/intellij/resources/icons_list/) provided as part of the [IntelliJ Platform UI Guidelines](https://jetbrains.design/intellij/) under the [MIT License](https://github.com/JetBrains/ui/blob/master/LICENSE) used for this project?

**Comment by c5inco** [comment]
@mishinalina can confirm

**Comment by bulenkov** [comment]
@c5inco @dstovall No, they are under Apache 2.0 license. The LICENSE file was incorrect and had the wrong copyright. Now it's updated. For icons with JetBrains logo please follow https://www.jetbrains.com/company/brand/
