### ISSUE TITLE
Table selection state clarification

### ISSUE THREAD

**Issue by lppedd** [JetBrains/ui#29]
In the guidelines you write

> Do not leave the active selection color in the table when the focus switches to some other element. It is otherwise confusing which element is currently active.

Just to better understand, should one implement this himself? Or should this be implemented at platform level?
I ask because this behavior isn't present at standard (e.g. `JBTable`), and I had to write my own logic with focus listeners.

```kotlin
addFocusListener(object : FocusListener {
   override fun focusGained(e: FocusEvent?) {
      updateColorsForFocusState(isFocused = true)
   }

   override fun focusLost(event: FocusEvent?) {
      updateColorsForFocusState(isFocused = false)
   }

   private fun updateColorsForFocusState(isFocused: Boolean) {
      setSelectionForeground(UIUtil.getTableSelectionForeground(isFocused))
      setSelectionBackground(UIUtil.getTableSelectionBackground(isFocused))
   }
})
```

Thanks 😄

**Comment by lppedd** [comment]
Also I would like to understand what to do in this case. Should the selection still be active when I press "OK"?

![focus](https://user-images.githubusercontent.com/19871649/98820052-f3f54d80-242d-11eb-9d21-67eb5a6115b5.gif)

**Comment by karollewandowski** [comment]
The issue has been transferred to https://youtrack.jetbrains.com/issue/IJSDK-2069/UI-Guidelines-Table-selection-state-clarification
