### ISSUE TITLE
missing ExtendableTextField

### ISSUE THREAD

**Issue by gdueck** [JetBrains/ui#30]
https://jetbrains.github.io/ui/controls/built_in_button/#03 says "To place a button inside a text field, use the com.intellij.ui.components.fields.ExtendableTextField class and its addExtension method."
There is no further documentation on ExtendableTextField, and no jar file can be found that contains package com.intellij.ui.components.fields .

This is a bug in the sense that the documentation is clearly referring to a unicorn. Either the documentation page should be revised or the unicorn should be produced.

**Comment by lppedd** [comment]
Hi @gdueck, months ago I've successfully used the `ExtendableTextField` in my project.  
Are you sure you're targeting the right version of IDEA?

https://github.com/lppedd/idea-conventional-commit/blob/master/src/main/kotlin/com/github/lppedd/cc/ui/VerifiableExtendableTextField.kt

**Comment by karollewandowski** [comment]
The current code snippet is verified and correct.
