### ISSUE TITLE
Validation errors guideline recommends to use project as Disposable

### ISSUE THREAD

**Issue by elmot** [JetBrains/ui#33]
while https://plugins.jetbrains.com/docs/intellij/disposers.html strongly discourages that

**Comment by lppedd** [comment]
If I remember correctly there are certain situation where there is no way to establish when a resource should be disposed.  
Also, does it make sense to create a new `Disposable` with a `Project` as parent? It's ok to pass the project itself imho.

**Comment by elmot** [comment]
This is not OK to have a Project or an Application as a disposable, that may lead to resource leaks, that is stated in the official documentation, in the red box https://plugins.jetbrains.com/docs/intellij/disposers.html#choosing-a-disposable-parent
I believe that a good solution is to have a visual form or an UI control as the Disposable for most of the cases. It might be that some UI form base class may implement Disposable.

**Comment by lppedd** [comment]
@elmot it's true that for certain plugins it might cause memory leaks (the no-restart ones), but there are certain UI elements which still are not notified when being disposed. For example - until recently - a `ConfigurableUi` didn't get called when disposed, so I had to attach to the project instead.

**Comment by YannCebron** [comment]
Code samples have been updated https://plugins.jetbrains.com/docs/intellij/validation-errors.html
