### ISSUE TITLE
Icons list is not up to date

### ISSUE THREAD

**Issue by mallowigi** [JetBrains/ui#42]
https://jetbrains.design/intellij/resources/icons_list/

This document is a few months old, who is in charge of updating it?

**Comment by c5inco** [comment]
Thanks for the reminder - we try to update it at least once a quarter but perhaps we should move to once a month. ;) The live site should be updated now.

**Comment by c5inco** [comment]
@mallowigi just curious - is there a specific set of icons that you expected to see?

**Comment by mallowigi** [comment]
I am in charge of an icon theme, and I need to follow around icon additions and updates

**Comment by mallowigi** [comment]
Hi, reupping this since this is out of date once again.

Thanks!
