### ISSUE TITLE
Permission to use JetBrains icons in my plugin

### ISSUE THREAD

**Issue by Dragon-0609** [JetBrains/ui#44]
Hi. I'm developing a plugin for PascalABC.NET IDE.  Its name is `Yuki Theme`. [Here's link](https://github.com/Dragon-0609/Yuki-Theme) to the repo. I want to use JetBrains icons in my plugin.

PascalABC.NET IDE without my plugin:

![bandicam 2021-12-21 19-15-14-069](https://user-images.githubusercontent.com/80271099/146945246-f4d745eb-d99d-4eed-b461-c4a727114369.png)

with my plugin:

![bandicam 2021-12-21 19-14-49-043](https://user-images.githubusercontent.com/80271099/146945281-a275d643-d105-47c0-b187-0e4ade53cfef.png)

Window of my plugin:

![bandicam 2021-12-21 19-15-54-147](https://user-images.githubusercontent.com/80271099/146945330-bf3ca42b-b184-4765-9473-9897296d3743.png)

Icons of PascalABC.NET:

![bandicam 2021-12-20 18-09-53-230_icons](https://user-images.githubusercontent.com/80271099/146945382-2502da91-65c5-41cb-b1c6-02045d4ce871.png)

I want to use the icons to change the default icons of the IDE and icons of my pluign's window.
Can I use the icons in my plugin? I promise I'll add [JetBrains.Icons](https://jetbrains.design/intellij/resources/icons_list/) to the used list:

![bandicam 2021-12-21 19-20-43-294](https://user-images.githubusercontent.com/80271099/146945690-4304ce36-9f81-4096-aa0a-3a40caac840b.png)

**Comment by Dragon-0609** [comment]
I have read the license. If I'm not wrong, I can use [JetBrains](https://jetbrains.design/intellij/resources/icons_list/) following the [license](https://github.com/JetBrains/ui/blob/069ca60ad0f7f292e045d514eaffbe56faa8e0b3/LICENSE#L90).

**Comment by c5inco** [comment]
Yep that is correct. A [bit more details](https://github.com/JetBrains/ui/issues/27#issuecomment-766708521) here if you plan to use the JetBrains logo also
