### ISSUE TITLE
Fix sample code in "Validation errors"

### ISSUE THREAD

**Issue by YannCebron** [JetBrains/ui#50]
https://jetbrains.design/intellij/principles/validation_errors/#implementation

contains sample code

`new ComponentValidator(project)` ....

but `Project` should not be used here, instead use e.g. `com.intellij.openapi.options.SettingsEditor` instance, `com.intellij.openapi.ui.DialogWrapper#getDisposable`, ...

**Comment by karollewandowski** [comment]
Also, `ComponentValidator.withValidator(@NotNull Consumer<? super ComponentValidator> validator)` is used, which is deprecated.
`ComponentValidator.withValidator(@NotNull Supplier<? extends ValidationInfo> validator)` should be used instead.

**Comment by YannCebron** [comment]
updated https://plugins.jetbrains.com/docs/intellij/validation-errors.html
