### ISSUE TITLE
Advertising quick-fix availability in inspection description

### ISSUE THREAD

**Issue by rillig** [JetBrains/ui#52]
https://jetbrains.design/intellij/text/inspections/#13 says about inspection descriptions:
> Provide details, such as:
> * A quick-fix if applicable:
>     > Suggests inserting the import statement

Most of the 'unused import' inspections don't follow this advice.
Mentioning the quick-fix as part of an example sounds fine to me,
but I don't see the point of mentioning separately that a quick-fix exists.

For example, VueMissingComponentImportInspection.html says:
> Reports Vue components, which require to be imported in Vue templates.
> It provides a quick-fix to add the missing import.

Intuitively, I would have removed the second sentence from the inspection description.
The quick-fix of adding the missing import is so obvious to me that I don't see why it should be mentioned.
In general, if the inspection supports a quick-fix, the user will see it in context.

What are the reasons for suggesting that inspections describe their quick-fixes separately from providing example code?

**Comment by rillig** [comment]
Another example is `EqualsCalledOnEnumConstant.html`, which contains this sentence:
> A quick-fix is available to change the call to a comparison.
> …
> After the quick-fix is applied:
> …

The first of these sentences looks redundant to me.

**Comment by karollewandowski** [comment]
The issue has been transferred to https://youtrack.jetbrains.com/issue/IJSDK-2070/UI-Guidelines-Advertising-quick-fix-availability-in-inspection-description
