### ISSUE TITLE
Durations that are updated regularly

### ISSUE THREAD

**Issue by rillig** [JetBrains/ui#55]
https://jetbrains.design/intellij/principles/data_formats/#duration

Some labels show a duration that is updated in small intervals, typically several times per second.
One example is for the duration of running unit tests.
In cases like that, the width of the label should not change frequently, to avoid flickering or jumping around on the screen.
Could you perhaps add a sentence about that topic?
For example, in the duration of unit tests, the milliseconds should always be displayed using 3 digits, even if the last digit is 0.

**Comment by karollewandowski** [comment]
The issue has been transferred: https://youtrack.jetbrains.com/issue/IJSDK-2072/UI-Guidelines-Durations-that-are-updated-regularly
