### ISSUE TITLE
Icons list page is blank on Safari

### ISSUE THREAD

**Issue by mlytvyn** [JetBrains/ui#57]
Works fine in Chrome/Arc/Firefox.

https://jetbrains.github.io/ui/resources/icons_list/

Same for both Dark & Light appearance
Safari version: Version 16.4 (18615.1.26.11.22)

<img width="895" alt="image" src="https://user-images.githubusercontent.com/2292510/231095882-8bb0ecff-77c7-4938-b51d-d6b53da65677.png">

**Comment by c5inco** [comment]
Hmm it should be working. I just tested it now.

**Comment by mlytvyn** [comment]
hello @c5inco , there is one more message
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/2292510/233769246-b1c04b51-f1cf-4fcc-89d2-f01debed21cb.png">

I'm able to open `https://intellij-icons.jetbrains.design` directly.

**Comment by mlytvyn** [comment]
resolved by itself :)
