### ISSUE TITLE
Can't find ComponentValidator when using Grade IntelliJ plugin

### ISSUE THREAD

**Issue by jeffmaury** [JetBrains/ui#8]
Trying to follow https://jetbrains.github.io/ui/principles/validation_errors but I can't find the ComponentValidator  with my plugin project which is Gradle based. If I ask IJ to generate a plugin project, then I can find the class in platform-api.jar but the one which is brought by the Gradle IJ plugin does not contain this class.
Any clue ?

**Comment by zolotov** [comment]
No clue. It works just fine for me in Gradle IJ plugin project. What `intellij.version` you have set?

![image](https://user-images.githubusercontent.com/140920/52208792-de371980-2892-11e9-9265-369d77a97ecb.png)

**Comment by jeffmaury** [comment]
I'm using IC-2018.1

**Comment by zolotov** [comment]
ComponentValidator was added in `2018.3`: https://github.com/JetBrains/intellij-community/commits/master/platform/platform-api/src/com/intellij/openapi/ui/ComponentValidator.java
